title: Kirsten Currie
logo: /assets/img/profile_picture.png
#description: Data Analyst Portfolio
#show_downloads: true
github_username: kirstencurrie
linkedin_username: kirstencurrie
theme: jekyll-theme-minimal
google_analytics: G-T850KJ2HC9
